from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .canonical import content_hash
from .policy import validate_policy_pack

POLICY_EXPORT_SCHEMA = "trustai.policy-backend-export/0.1"

PROOF_DECAY_TO_AGE_FIELD = {
    "max_gate_age_hours": "gate",
    "max_soak_age_hours": "soak",
    "max_runtime_attestation_age_hours": "runtime_attestation",
    "max_shadow_replay_age_hours": "shadow_replay",
}


def export_policy_pack(
    policy_pack: dict[str, Any],
    *,
    target: str = "all",
    package: str = "trustai.runtime",
    namespace: str = "TrustAI",
) -> dict[str, Any]:
    validate_policy_pack(policy_pack)
    if target not in {"all", "opa", "cedar"}:
        raise ValueError("target must be all, opa, or cedar")

    targets: dict[str, Any] = {}
    if target in {"all", "opa"}:
        targets["opa_rego"] = {
            "language": "rego",
            "package": package,
            "input_contract": _opa_input_contract(policy_pack),
            "module": build_opa_rego(policy_pack, package=package),
        }
    if target in {"all", "cedar"}:
        targets["cedar"] = build_cedar_policy_set(policy_pack, namespace=namespace)

    payload = {
        "schema": POLICY_EXPORT_SCHEMA,
        "policy_pack_id": policy_pack["id"],
        "policy_pack_version": policy_pack["version"],
        "policy_pack_hash": content_hash(policy_pack),
        "targets": targets,
    }
    payload["payload_hash"] = content_hash(payload)
    return payload


def build_opa_rego(policy_pack: dict[str, Any], *, package: str = "trustai.runtime") -> str:
    validate_policy_pack(policy_pack)
    lines = [
        "# Generated by TrustAI from a trustai.policy-pack/0.1 document.",
        "# The caller supplies input.proof.gate_outcome and precomputed proof ages under input.proof.age_hours.",
        f"package {package}",
        "",
        "default allow = false",
        "",
        "allow {",
        "  proof_fresh",
        "  count(deny_matches) == 0",
        "  count(missing_approvals) == 0",
        "}",
        "",
    ]

    lines.extend(_rego_proof_freshness(policy_pack))
    lines.append("")
    lines.extend(
        [
            "approval_present(role) {",
            "  approval := input.action.approvals[_]",
            "  approval.role == role",
            '  approval.approved_at != ""',
            "}",
            "",
            "approval_present(role) {",
            "  approval := input.action.approval",
            "  approval.role == role",
            '  approval.approved_at != ""',
            "}",
            "",
            "approval_present_any {",
            "  approval := input.action.approvals[_]",
            '  approval.approved_at != ""',
            "}",
            "",
            "approval_present_any {",
            "  approval := input.action.approval",
            '  approval.approved_at != ""',
            "}",
            "",
        ]
    )

    for rule in policy_pack.get("rules", []):
        effect = rule.get("effect", "deny")
        conditions = [_rego_condition(condition) for condition in rule.get("conditions", [])]
        if not conditions:
            conditions = ["true"]
        if effect == "deny":
            lines.extend(_rego_set_rule("deny_matches", rule["id"], conditions))
        elif effect == "require_approval":
            approval = (
                f'not approval_present({json.dumps(rule["approval_role"])})'
                if rule.get("approval_role")
                else "not approval_present_any"
            )
            lines.extend(_rego_set_rule("missing_approvals", rule["id"], [*conditions, approval]))
        elif effect == "allow":
            lines.extend(_rego_set_rule("allow_matches", rule["id"], conditions))
        else:
            raise ValueError(f"unsupported policy effect: {effect}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_cedar_policy_set(policy_pack: dict[str, Any], *, namespace: str = "TrustAI") -> dict[str, Any]:
    validate_policy_pack(policy_pack)
    policies: list[dict[str, Any]] = []

    policies.append(
        {
            "id": "proof-active-gate-passed",
            "effect": "forbid",
            "principal": f"{namespace}::Agent",
            "action": f'{namespace}::Action::"runtime_action"',
            "resource": f"{namespace}::Contract",
            "condition": 'context.proof.gate_outcome != "passed"',
            "source_policy_key": "active_proof_pack",
        }
    )

    for policy_key, age_field in PROOF_DECAY_TO_AGE_FIELD.items():
        threshold = policy_pack.get("proof_decay", {}).get(policy_key)
        if threshold is None:
            continue
        policies.append(
            {
                "id": f"proof-decay-{policy_key}",
                "effect": "forbid",
                "principal": f"{namespace}::Agent",
                "action": f'{namespace}::Action::"runtime_action"',
                "resource": f"{namespace}::Contract",
                "condition": f"context.proof.age_hours.{age_field} > {json.dumps(threshold)}",
                "source_policy_key": policy_key,
            }
        )

    for rule in policy_pack.get("rules", []):
        effect = rule.get("effect", "deny")
        conditions = [_cedar_condition(condition) for condition in rule.get("conditions", [])]
        if effect == "deny":
            cedar_effect = "forbid"
        elif effect == "require_approval":
            cedar_effect = "forbid"
            approval = (
                f'!hasApproval({json.dumps(rule["approval_role"])})'
                if rule.get("approval_role")
                else "!hasAnyApproval()"
            )
            conditions.append(approval)
        elif effect == "allow":
            cedar_effect = "permit"
        else:
            raise ValueError(f"unsupported policy effect: {effect}")
        policies.append(
            {
                "id": rule["id"],
                "effect": cedar_effect,
                "principal": f"{namespace}::Agent",
                "action": f'{namespace}::Action::"runtime_action"',
                "resource": f"{namespace}::Contract",
                "condition": " && ".join(conditions) if conditions else "true",
                "trustai_effect": effect,
                "description": rule.get("description"),
            }
        )

    return {
        "language": "cedar-json",
        "schema": "trustai.cedar-policy-set/0.1",
        "namespace": namespace,
        "notes": [
            "Cedar-shaped review artifact; production deployments should translate helper functions into their Cedar schema.",
            "hasApproval(role) and hasAnyApproval() represent approval context supplied by the caller.",
        ],
        "policies": policies,
    }


def write_policy_export(path: str | Path, payload: dict[str, Any]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _opa_input_contract(policy_pack: dict[str, Any]) -> dict[str, Any]:
    proof_decay = policy_pack.get("proof_decay", {})
    return {
        "action": "runtime action payload supplied to trustai policy-check",
        "proof": {
            "gate_outcome": "must equal passed",
            "age_hours": {
                age_field: f"required when {policy_key} is set"
                for policy_key, age_field in PROOF_DECAY_TO_AGE_FIELD.items()
                if proof_decay.get(policy_key) is not None
            }
        },
        "approvals": "input.action.approvals[] or input.action.approval",
    }


def _rego_proof_freshness(policy_pack: dict[str, Any]) -> list[str]:
    checks: list[str] = ['input.proof.gate_outcome == "passed"']
    for policy_key, age_field in PROOF_DECAY_TO_AGE_FIELD.items():
        threshold = policy_pack.get("proof_decay", {}).get(policy_key)
        if threshold is not None:
            checks.append(f"input.proof.age_hours.{age_field} <= {json.dumps(threshold)}")
    if not checks:
        checks = ["true"]
    return ["proof_fresh {", *[f"  {check}" for check in checks], "}"]


def _rego_set_rule(name: str, rule_id: str, conditions: list[str]) -> list[str]:
    return [
        f"{name}[{json.dumps(rule_id)}] {{",
        *[f"  {condition}" for condition in conditions],
        "}",
    ]


def _rego_condition(condition: dict[str, Any]) -> str:
    return f"{_rego_field(condition['field'])} {condition['operator']} {json.dumps(condition.get('value'))}"


def _cedar_condition(condition: dict[str, Any]) -> str:
    return f"{_cedar_field(condition['field'])} {condition['operator']} {json.dumps(condition.get('value'))}"


def _rego_field(field: str) -> str:
    return "input." + ".".join(part for part in field.split(".") if part)


def _cedar_field(field: str) -> str:
    parts = [part for part in field.split(".") if part]
    if parts and parts[0] in {"action", "proof", "policy"}:
        return "context." + ".".join(parts)
    return "context." + ".".join(parts)
